- hosts: bdt
  remote_user: vagrant
  gather_facts: no
  tasks:
    - name: kill bdt
      shell: sudo killall bdt
      ignore_errors: yes
    - name: clean the testbed directory
      shell: rm -rf /home/vagrant/bdt-testbed