- hosts: bdt
  remote_user: vagrant
  gather_facts: no
  tasks:
    - name: create testbed dirs
      file:
        path: /home/vagrant/bdt-testbed
        state: directory
    - name: run bdt as a daemon
      shell: "(nohup ./bdt > /home/vagrant/bdt-testbed/log0.txt 2>&1 &)"
      args:
        chdir: /home/vagrant/bdt